<?php

namespace Database\Seeders;

use App\Models\MenuItem;
use Illuminate\Database\Seeder;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $menuItems = [
            [
                'name' => 'Classic Croissant',
                'description' => 'Buttery, flaky croissant baked fresh daily. The perfect start to your morning.',
                'category' => 'Pastries',
                'price' => 280.00,
                'image' => 'https://images.unsplash.com/photo-1555507036-ab794f4afe5b?w=400&h=300&fit=crop',
                'preparation_time' => 'Fresh baked',
                'ingredients' => json_encode(['Flour', 'Butter', 'Yeast', 'Salt']),
                'allergens' => json_encode([]),
                'calories' => 220,
                'status' => 'active',
            ],
            [
                'name' => 'Chocolate Croissant',
                'description' => 'Flaky pastry filled with rich dark chocolate. A decadent morning treat.',
                'category' => 'Pastries',
                'price' => 350.00,
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
                'preparation_time' => 'Fresh baked',
                'ingredients' => json_encode(['Flour', 'Butter', 'Dark chocolate', 'Yeast']),
                'allergens' => json_encode(['Gluten', 'Dairy']),
                'calories' => 320,
                'status' => 'active',
            ],
            [
                'name' => 'Artisan Sourdough',
                'description' => 'Traditional sourdough bread with a perfect crust and tangy flavor. Made with our signature starter.',
                'category' => 'Fresh Bread',
                'price' => 450.00,
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
                'preparation_time' => 'Fresh daily',
                'ingredients' => json_encode(['Sourdough starter', 'Flour', 'Water', 'Salt']),
                'allergens' => json_encode(['Gluten']),
                'calories' => 180,
                'status' => 'active',
            ],
            [
                'name' => 'Strawberry Tart',
                'description' => 'Delicate pastry shell filled with vanilla custard and topped with fresh strawberries. Sweet perfection.',
                'category' => 'Cakes & Desserts',
                'price' => 480.00,
                'image' => 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400&h=300&fit=crop',
                'preparation_time' => 'Made fresh',
                'ingredients' => json_encode(['Pastry shell', 'Vanilla custard', 'Fresh strawberries', 'Glaze']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 280,
                'status' => 'active',
            ],
            [
                'name' => 'Blueberry Muffin',
                'description' => 'Fluffy muffin bursting with fresh blueberries. Perfect for hot days.',
                'category' => 'Breakfast Items',
                'price' => 320.00,
                'image' => 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=400&h=300&fit=crop',
                'preparation_time' => 'Fresh baked',
                'ingredients' => json_encode(['Flour', 'Fresh blueberries', 'Eggs', 'Butter']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 280,
                'status' => 'active',
            ],
            [
                'name' => 'Vanilla Eclair',
                'description' => 'Light choux pastry filled with vanilla cream and topped with chocolate glaze. A delightful treat.',
                'category' => 'Cakes & Desserts',
                'price' => 420.00,
                'image' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
                'preparation_time' => 'Made fresh',
                'ingredients' => json_encode(['Choux pastry', 'Vanilla cream', 'Chocolate glaze']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 280,
                'status' => 'active',
            ],
            [
                'name' => 'Ceylon Tea',
                'description' => 'Authentic Sri Lankan black tea with rich flavor and golden color. A local favorite.',
                'category' => 'Beverages',
                'price' => 380.00,
                'image' => 'https://images.unsplash.com/photo-1597318374671-96ee162414ca?w=400&h=300&fit=crop',
                'preparation_time' => 'Freshly brewed',
                'ingredients' => json_encode(['Ceylon tea leaves', 'Hot water']),
                'allergens' => json_encode([]),
                'calories' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Cinnamon Roll',
                'description' => 'Soft, sweet roll swirled with cinnamon and topped with cream cheese glaze.',
                'category' => 'Breakfast Items',
                'price' => 380.00,
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
                'preparation_time' => 'Warm & fresh',
                'ingredients' => json_encode(['Flour', 'Cinnamon', 'Brown sugar', 'Cream cheese']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 350,
                'status' => 'active',
            ],
            [
                'name' => 'Artisan Baguette',
                'description' => 'Traditional French baguette with crispy crust and soft interior. Perfect with your morning coffee.',
                'category' => 'Fresh Bread',
                'price' => 320.00,
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
                'preparation_time' => 'Fresh daily',
                'ingredients' => json_encode(['Flour', 'Water', 'Yeast', 'Salt']),
                'allergens' => json_encode(['Gluten']),
                'calories' => 180,
                'status' => 'active',
            ],
            [
                'name' => 'Red Velvet Cake',
                'description' => 'Moist red velvet cake with cream cheese frosting. A classic favorite.',
                'category' => 'Cakes & Desserts',
                'price' => 580.00,
                'image' => 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400&h=300&fit=crop',
                'preparation_time' => 'Made fresh',
                'ingredients' => json_encode(['Flour', 'Cocoa', 'Cream cheese', 'Red food coloring']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 420,
                'status' => 'active',
            ],
            [
                'name' => 'Fresh Coffee',
                'description' => 'Rich, aromatic coffee blend perfect with our pastries. A perfect treat for coffee lovers.',
                'category' => 'Beverages',
                'price' => 380.00,
                'image' => 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop',
                'preparation_time' => 'Freshly brewed',
                'ingredients' => json_encode(['Coffee beans', 'Hot water']),
                'allergens' => json_encode([]),
                'calories' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Danish Pastry',
                'description' => 'Flaky Danish pastry with sweet filling. Simple, sweet, and satisfying.',
                'category' => 'Pastries',
                'price' => 420.00,
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
                'preparation_time' => 'Fresh baked',
                'ingredients' => json_encode(['Flour', 'Butter', 'Fruit filling']),
                'allergens' => json_encode(['Gluten', 'Dairy']),
                'calories' => 320,
                'status' => 'active',
            ],
            [
                'name' => 'Lemon Tart',
                'description' => 'Tangy lemon curd in a crisp pastry shell. A refreshing and energizing treat.',
                'category' => 'Cakes & Desserts',
                'price' => 450.00,
                'image' => 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400&h=300&fit=crop',
                'preparation_time' => 'Made fresh',
                'ingredients' => json_encode(['Lemon curd', 'Pastry shell', 'Meringue']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 250,
                'status' => 'active',
            ],
            [
                'name' => 'Double Chocolate Muffin',
                'description' => 'Rich chocolate muffin with chocolate chips. Freshly baked daily and perfect with your morning beverage.',
                'category' => 'Breakfast Items',
                'price' => 380.00,
                'image' => 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=400&h=300&fit=crop',
                'preparation_time' => 'Fresh baked',
                'ingredients' => json_encode(['Flour', 'Chocolate chips', 'Eggs', 'Butter', 'Sugar']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 420,
                'status' => 'active',
            ],
            [
                'name' => 'Caramel Macaron',
                'description' => 'Delicate almond macaron filled with salted caramel. Perfect for hot days.',
                'category' => 'Cakes & Desserts',
                'price' => 180.00,
                'image' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
                'preparation_time' => 'Made fresh',
                'ingredients' => json_encode(['Almond flour', 'Egg whites', 'Caramel filling']),
                'allergens' => json_encode(['Nuts', 'Eggs']),
                'calories' => 120,
                'status' => 'active',
            ],
            [
                'name' => 'Banana Bread',
                'description' => 'Moist banana bread made with ripe bananas, topped with walnuts.',
                'category' => 'Fresh Bread',
                'price' => 350.00,
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
                'preparation_time' => 'Fresh daily',
                'ingredients' => json_encode(['Ripe bananas', 'Flour', 'Walnuts', 'Butter']),
                'allergens' => json_encode(['Gluten', 'Nuts', 'Dairy']),
                'calories' => 280,
                'status' => 'active',
            ],
            [
                'name' => 'Chai Latte',
                'description' => 'Aromatic spiced tea blend with steamed milk and a touch of honey. Warming and comforting.',
                'category' => 'Beverages',
                'price' => 420.00,
                'image' => 'https://images.unsplash.com/photo-1597318374671-96ee162414ca?w=400&h=300&fit=crop',
                'preparation_time' => 'Freshly brewed',
                'ingredients' => json_encode(['Chai tea blend', 'Steamed milk', 'Honey', 'Cinnamon']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 200,
                'status' => 'active',
            ],
            [
                'name' => 'Vanilla Cupcake',
                'description' => 'Fluffy vanilla cupcake with vanilla buttercream frosting. A classic favorite with a sweet twist.',
                'category' => 'Cakes & Desserts',
                'price' => 280.00,
                'image' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
                'preparation_time' => 'Fresh baked',
                'ingredients' => json_encode(['Flour', 'Vanilla extract', 'Buttercream', 'Eggs']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 320,
                'status' => 'active',
            ],
            [
                'name' => 'Blueberry Scone',
                'description' => 'Tender scone loaded with fresh blueberries, served with clotted cream.',
                'category' => 'Breakfast Items',
                'price' => 420.00,
                'image' => 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=400&h=300&fit=crop',
                'preparation_time' => 'Fresh baked',
                'ingredients' => json_encode(['Flour', 'Fresh blueberries', 'Eggs', 'Butter', 'Cream']),
                'allergens' => json_encode(['Gluten', 'Dairy', 'Eggs']),
                'calories' => 380,
                'status' => 'active',
            ],
            [
                'name' => 'Iced Tea',
                'description' => 'Refreshing iced tea with a light and crisp flavor. Antioxidant-rich and energizing.',
                'category' => 'Beverages',
                'price' => 320.00,
                'image' => 'https://images.unsplash.com/photo-1597318374671-96ee162414ca?w=400&h=300&fit=crop',
                'preparation_time' => 'Freshly brewed',
                'ingredients' => json_encode(['Tea leaves', 'Cold water', 'Ice', 'Lemon']),
                'allergens' => json_encode([]),
                'calories' => 10,
                'status' => 'active',
            ],
        ];

        foreach ($menuItems as $item) {
            MenuItem::create($item);
        }
    }
}
